### ISSUE TITLE
Data for detector view

### ISSUE THREAD

**Issue by AdamGarnsworthy** [GRIFFINCollaboration/griffinMarkII#74]
The summary views of the detectors "GRIFFIN" and "SCEPTAR" for example. The data for these should come from the ODB under / DAQ / params / grif16 / there is a 'template' folder and a 'custom' folder there. Inside template there is a folder for the default parameters of each detector type. The GRIF-16s load their parameters from here, first from the template and then if any custom settings exist for each channel. They complain if they do not get them correctly so we can be certain that these values are what is being used.

In addition to re-routing the source of the data, I would like to add a drop-down menu in order to display any parameter that is found in the template folder. Human readable name equivalents for these parameters should be used as is down in the grifadc webpage interface.

**Comment by katieannemills** [comment]
- Just the summary views? What about the detail views (like if you click down to one GRIFFIN clover)? I would keep it consistent or else things will be super confusing.
- If I understand correctly, this replaces the 'Threshold' view with that dropdown you want, but the HV, trigger request and trigger accept views remain unchanged, polled directly from the ADCs.
- If a channel doesn't get an ODB parameter correctly, where and how exactly does it complain? That will need to be more front-and-center if the dashboard is reporting settings rather than report-backs.

**Comment by AdamGarnsworthy** [comment]
-all views
-correct
-Ok fair point. At the moment the GRIF-16 interface continues to poll the ODB for its values, indicated by a moving progress bar above the value. You will have to speak to Bryerton about maybe we have a status bit in the ODB for each digitizer to indicate if present values are loaded or not.
